### PR TITLE
Update tsconfig.json

### PR DESCRIPTION
**Pull request by multics**
Output es2015 `normalizeComponent` function

### CODE REVIEW

**Comment by znck** [comment]
Rollup build generates cjs build (with  es2015) content.

https://github.com/znck/vue-runtime-helpers/blob/45179016f62b9db492ade262368406e036be66fe/rollup.config.js#L15

**Comment by multics** [comment]
When using `rollup-plugin-vue`, it still generates `es6` function of `normalizeComponent`. Is there any configuration item to pass to use this `cjs` output?

**Comment by multics** [comment]
It seems `rollup-plugin-vue` always use `es6` version of `normalizeComponent`. Is there any option to use this `cjs` output? And I looked into the npm package - `vue-runtime-helpers` which comes with `rollup-plugin-vue` I believe, only `es6` version is included.

**Comment by multics** [comment]
I figured out a hack way in `rollup.config.js` to make the code transformed.

```
import * as babel_compiler from '@babel/core'
const { code } = babel_compiler.transform(fs.readFileSync(fullpath('node_modules/vue-runtime-helpers/normalize-component.js'), 'utf8'), { presets: ['@babel/preset-env'], plugins: ['@babel/plugin-transform-runtime'] })
```

and 
```
    plugins: [
      vue({
        css: false,
        normalizer: code
      }),
...
```

**Comment by znck** [comment]
Use https://github.com/rollup/rollup-plugin-node-resolve to resolve package from `main` field instead of `module`.

**Comment by multics** [comment]
I found that the `rollup-plugin-vue` is still `4.6.1` on `npmjs` site, could you please release the `4.6.2`?

It seems `4.6.2` depends on `vue-runtime-helpers` `1.0.0`, and `4.6.1` depends on previous version.

**Comment by znck** [comment]
I am not sure how I missed that, anyways done now. Thanks for reporting.

**Comment by multics** [comment]
THANK YOU!

**Pull request closed without merging**
